README.create
chiezoo1991/chat-space2 pull request #1
Opened 2019-02-18 10:52 UTC by chiezoo1991

READMEを編集した

2019-02-18 11:56 UTC, TOMARUMARU reviewed
membersテーブルはusersとgroupsの中間テーブルとなります。
中間テーブルを用いた多対多のアソシエーションについて調べて修正をお願いします。

2019-02-19 10:35 UTC, chiezoo1991 commented
編集しました

2019-02-21 09:59 UTC, TOMARUMARU reviewed
中間テーブルを用いた多対多のアソシエーションの理解がまだ甘いので、調べて分からなければメンターにご質問ください。

2019-02-21 09:59 UTC, TOMARUMARU commented on app/controllers/messeages_controller.rb
> +class MesseagesController < ApplicationController
DB設計のPRなのでこちらは上げないでください。

2019-02-22 12:40 UTC, chiezoo1991 commented
編集しました。

2019-02-22 12:43 UTC, TOMARUMARU commented on README.md
> +|user_id|integer|null: false, foreign_key: true|
referencesで定義しましょう

2019-02-22 12:45 UTC, TOMARUMARU commented on README.md
> +|group_id|integer|null: false, foreign_key: true|
referencesで定義しましょう

2019-02-22 12:45 UTC, TOMARUMARU commented on README.md
> +|name|string|null: false, foreign_key: true|
外部キーをつけてる意図はなんでしょうか？他の箇所も同様です

2019-02-22 12:45 UTC, TOMARUMARU commented on README.md
> +|group_name|string|null: false, foreign_key: true|
nameで大丈夫です

2019-02-22 12:45 UTC, TOMARUMARU commented on README.md
> +|user_id|integer|null: false, foreign_key: true|
user_idは中間テーブルで管理します

2019-02-22 12:45 UTC, TOMARUMARU commented on README.md
> +|group_id|string|null: false, foreign_key: true|
referencesで定義しましょう

2019-02-22 12:45 UTC, TOMARUMARU commented on README.md
> +|user_id|integer|null: false, foreign_key: true|
referencesで定義しましょう

2019-02-22 12:45 UTC, TOMARUMARU commented on README.md
> +|body|text|null: false, foreign_key: true|
null: false外しましょう

2019-02-22 12:45 UTC, TOMARUMARU commented on README.md
> +|timestamps|datetime|null: false, foreign_key: true|
created_atあるのでいいかと

2019-02-24 04:16 UTC, chiezoo1991 commented on README.md
> +|user_id|integer|null: false, foreign_key: true|
referencesで定義し直しました

2019-02-24 04:17 UTC, chiezoo1991 commented on README.md
> +|timestamps|datetime|null: false, foreign_key: true|
timestamps削除しました

2019-02-24 04:17 UTC, chiezoo1991 commented on README.md
> +|body|text|null: false, foreign_key: true|
外しました。

2019-02-24 04:17 UTC, chiezoo1991 commented on README.md
> +|user_id|integer|null: false, foreign_key: true|
referencesで定義しました。

2019-02-24 04:17 UTC, chiezoo1991 commented on README.md
> +|group_id|string|null: false, foreign_key: true|
referencesで定義しました。

2019-02-24 04:17 UTC, chiezoo1991 commented on README.md
> +|user_id|integer|null: false, foreign_key: true|
user_idの記載を削除しました。

2019-02-24 04:18 UTC, chiezoo1991 commented on README.md
> +|group_name|string|null: false, foreign_key: true|
nameへカラム名を変更しました。

2019-02-24 04:18 UTC, chiezoo1991 commented on README.md
> +|name|string|null: false, foreign_key: true|
外部キーを指定していた部分を削除しました。

2019-02-24 04:18 UTC, chiezoo1991 commented on README.md
> +|group_id|integer|null: false, foreign_key: true|
referencesで定義しました。

2019-02-24 04:40 UTC, ghost requested changes

2019-02-24 04:40 UTC, hiroki5123 commented on README.md
> +|references|integer|null: false, foreign_key: true|
ここのカラムは何になりますか？

2019-02-24 04:40 UTC, hiroki5123 commented on README.md
> +|references|integer|foreign_key: true|
ここのカラム名はなりますか？

2019-02-24 04:40 UTC, hiroki5123 commented on README.md
> +|references|string|foreign_key: true|
referencesは型の種類で、カラム名ではありません。
適切なカラム名を設定してください。

2019-02-24 04:56 UTC, chiezoo1991 commented on README.md
> +|references|integer|null: false, foreign_key: true|
userとgroupにカラム名を変更しました。
reference型を使うとここがそれぞれuser_id、group_idに変化するという理解で良いでしょうか？

2019-02-24 04:57 UTC, chiezoo1991 commented on README.md
> +|references|integer|foreign_key: true|
groupカラムでgroup_idに変化

2019-02-24 04:57 UTC, chiezoo1991 commented on README.md
> +|references|integer|foreign_key: true|
userカラムでuser_idへ変化

2019-02-24 04:58 UTC, chiezoo1991 commented on README.md
> +|references|string|foreign_key: true|
groupカラムでgroup_idへ変化

2019-02-24 05:10 UTC, hiroki5123 commented on README.md
> +|references|integer|null: false, foreign_key: true|
その理解で大丈夫です！

2019-02-24 05:11 UTC, hiroki5123 commented
修正をpushして変更を反映させてください

2019-02-24 05:18 UTC, yuki-uchida requested changes

2019-02-24 05:18 UTC, yuki-uchida commented on README.md
> +|body|text|foreign_key: true|
foreign_keyについて少し調べてみてください

2019-02-24 05:32 UTC, chiezoo1991 commented on README.md
> +|body|text|foreign_key: true|
bodyとimageにも外部キーがついていたので削除しました。

2019-02-24 05:35 UTC, yuki-uchida requested changes

2019-02-24 05:35 UTC, yuki-uchida commented on README.md
> +|name|string|null: false, foreign_key: true|
ここにもミスがありますね

2019-02-24 05:35 UTC, yuki-uchida commented on README.md
> +|group|integer|foreign_key: true|
こちらもミスがあります

2019-02-24 06:03 UTC, chiezoo1991 commented on README.md
> +|name|string|null: false, foreign_key: true|
nameについていた不要な外部キーを削除しました。

2019-02-24 06:03 UTC, chiezoo1991 commented on README.md
> +|group|integer|foreign_key: true|
reference型にTypeを変更しました。

2019-02-24 06:03 UTC, yuki-uchida requested changes
LGTMです。お疲れ様でした

2019-02-24 06:34 UTC, merged