Ajax.create
chiezoo1991/chat-space2 pull request #16
Opened 2019-03-19 11:52 UTC by chiezoo1991

非同期通信・スクロール作成

2019-03-19 11:56 UTC, chiezoo1991 commented
投稿後にスクロールされるという実装を書いたり調べたりもしていますがうまく行きません。
手詰まりなので、一旦その他の部分も含めプルリクエストを出します。アドバイスいただけると助かります。（そもそも非同期ができているのかも微妙です…）

投稿テキストのみ
https://gyazo.com/2c02a62846c34e5d5ceaa85ed11b7037

投稿画像のみ
https://gyazo.com/b8f508025b87bb94eff5448863deae11

投稿・画像
https://gyazo.com/05d96ec9ad6db0f7dade3d57de8d14b6

2019-03-19 12:03 UTC, ReoKuriyama reviewed
スクロールがうまくいかないという方は多くいらっしゃいますが、まずは調べてきたものをコピペでかく。それでも動かないのであれば、html, css を別ファイルで用意してこのプロジェクトから完全に切り離した状態で動くかテストしましょう。

2019-03-19 12:03 UTC, ReoKuriyama commented on app/controllers/messages_controller.rb
> +      format.html { redirect_to group_messages_path(@group), notice: 'メッセージが送信されました' }
htmlレスポンスはもう使わないのでここを削除したら非同期でメッセージ送信ができてるかわかります。

2019-03-20 12:46 UTC, chiezoo1991 commented
投稿テキストのみ
https://gyazo.com/efbd7fb43ce2534c5288c3dbbbb3655b

投稿画像のみ
https://gyazo.com/6807b498b415b4163358131effe72460

投稿・画像
https://gyazo.com/2ffc0553ec9e95a75515db79f1d16f78

連続投稿
https://gyazo.com/28491c37314a4139aa553f16e55cc7f1

SEND連打
https://gyazo.com/adea0375295438e46e429300664a8fe3

2019-03-20 12:49 UTC, TOMARUMARU reviewed
レビュー依頼でしょうか？
指摘されている箇所が修正されていなかったりしますが完成ですか？

2019-03-20 13:00 UTC, chiezoo1991 commented on app/controllers/messages_controller.rb
> +      format.html { redirect_to group_messages_path(@group), notice: 'メッセージが送信されました' }
＜記入場所間違えました＞
ご指摘部分変更しました。
投稿テキストのみ
https://gyazo.com/efbd7fb43ce2534c5288c3dbbbb3655b

投稿画像のみ
https://gyazo.com/6807b498b415b4163358131effe72460

投稿・画像
https://gyazo.com/2ffc0553ec9e95a75515db79f1d16f78

連続投稿
https://gyazo.com/28491c37314a4139aa553f16e55cc7f1

SEND連打
https://gyazo.com/adea0375295438e46e429300664a8fe3

2019-03-21 02:04 UTC, TOMARUMARU commented on app/assets/javascripts/messages.js
> +    if (message.image.url) {
三項演算子で書きましょう

2019-03-21 02:04 UTC, TOMARUMARU commented on app/assets/javascripts/messages.js
> +      $('.form__message').val('')
resetメソッドを使いましょう

2019-03-21 04:17 UTC, chiezoo1991 commented on app/assets/javascripts/messages.js
> +    if (message.image.url) {
三項演算子に書き直しました
var addImage = (message.image.url !== null)? `<img src="${message.image.url}">`:'';

2019-03-21 04:18 UTC, chiezoo1991 commented on app/assets/javascripts/messages.js
> +    if (message.image.url) {
ただ、こちらを記載するとメッセージ投稿後、メッセージ最下部までスクロールの機能がされなくなりました。

2019-03-21 04:26 UTC, yuki-uchida commented on app/assets/javascripts/messages.js
> +      $('.form__message').val('')
こちら対応されましたか？

2019-03-21 04:27 UTC, yuki-uchida requested changes

2019-03-21 04:27 UTC, yuki-uchida commented on app/assets/stylesheets/chat.scss
>        .upper-message {
この辺りもBEMにそったクラス命名をしましょう。その後アンバサンドを活用した省略系で書いてください

2019-04-09 11:44 UTC, chiezoo1991 commented on app/assets/javascripts/messages.js
> +    if (message.image.url) {
スペルミスでした。

2019-04-09 11:44 UTC, chiezoo1991 commented on app/assets/javascripts/messages.js
> +      $('.form__message').val('')
記入いたしました。

2019-04-09 11:45 UTC, chiezoo1991 commented on app/assets/stylesheets/chat.scss
>        .upper-message {
命名規則はうまくできているかわかりませんが、スクロール機能は作動できました。

2019-04-09 12:29 UTC, chiezoo1991 commented
＜投稿テキストのみ、連続投稿＞
https://gyazo.com/cb4b7c7307855a9055ec96fcbde3c74d

＜画像のみ＞
https://gyazo.com/20c55134f19e2195b65f8cb0a9cb6cef

＜テキスト＋画像＞
https://gyazo.com/e240b73654c57ff459405165ae6f0bf0

＜SEND連打＞
https://gyazo.com/e79d43040272d587f51c2642519b813a

2019-04-09 12:40 UTC, i-date approved these changes
コメントした箇所以外はLGTMです^^
コメントした箇所を修正しましたら、マージしましょう！

2019-04-09 12:40 UTC, i-date commented on app/assets/javascripts/user.js
> +    console.log(input);
こちら必要ないようでしたら削除しましょう。

2019-04-09 12:40 UTC, i-date commented on app/assets/javascripts/user.js
> +          console.log(input);
こちらも

2019-04-10 00:31 UTC, merged